# =============================================================================
# Claude Code Action - PR Review with Linear Integration
# =============================================================================
# This workflow performs comprehensive PR reviews and creates INDIVIDUAL Linear
# tickets for each issue found, enabling granular tracking and assignment.
#
# Features:
# - Automatic PR review on open/sync/ready events
# - Manual re-review via @claude comments
# - Creates SEPARATE Linear tickets per issue (not consolidated)
# - Links tickets to PR with proper metadata
# - Inline code comments for specific issues
# - Severity-based priority and labeling
#
# Required Secrets:
# - CLAUDE_CODE_OAUTH_TOKEN: OAuth token for Claude Code
# - LINEAR_API_KEY: Linear API key for creating issues
#
# Optional Secrets:
# - LINEAR_TEAM_ID: Default team ID (auto-detected if not provided)
# =============================================================================

name: Claude PR Review with Linear

on:
  # Auto-review on PR open/update
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

  # Manual re-review via @claude comment
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

# Prevent concurrent reviews on same PR
concurrency:
  group: claude-review-${{ github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: true

jobs:
  claude-review:
    # Run on PR events OR when @claude is mentioned
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude') && github.event.issue.pull_request) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better diff context

      - name: Run Claude PR Review with Linear
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          # Authentication (choose one)
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          # anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # Enable progress tracking
          track_progress: true

          # Linear Integration (built-in MCP server)
          linear_api_key: ${{ secrets.LINEAR_API_KEY }}
          # Optional: Specify default team (Claude will auto-detect if not provided)
          linear_team_id: ${{ secrets.LINEAR_TEAM_ID }}

          # Review instructions with Linear integration
          prompt: |
            ## Context
            - **Repository**: ${{ github.repository }}
            - **PR Number**: #${{ github.event.pull_request.number || github.event.issue.number }}
            - **PR Title**: ${{ github.event.pull_request.title || github.event.issue.title }}
            - **Author**: @${{ github.event.pull_request.user.login || github.event.issue.user.login }}
            - **PR URL**: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number || github.event.issue.number }}

            ## Task
            Perform a comprehensive code review of this pull request and create **SEPARATE Linear tickets for EACH distinct issue** found.

            ## Review Focus Areas

            ### 1. Security (CRITICAL Priority)
            - SQL injection, XSS, CSRF vulnerabilities
            - Hardcoded secrets, API keys, credentials
            - Authentication/authorization bypasses
            - Insecure deserialization
            - Path traversal vulnerabilities
            - Sensitive data exposure

            ### 2. Bugs & Correctness (HIGH Priority)
            - Logic errors and race conditions
            - Null/undefined handling
            - Off-by-one errors
            - Resource leaks (memory, file handles, connections)
            - Error handling gaps
            - Edge case handling

            ### 3. Performance (HIGH/MEDIUM Priority)
            - N+1 query problems
            - Unbounded loops or recursion
            - Missing pagination/limits
            - Inefficient algorithms (O(n²) when O(n) possible)
            - Memory-intensive operations
            - Missing caching opportunities

            ### 4. Code Quality (MEDIUM Priority)
            - SOLID principles violations
            - DRY violations (duplicated code)
            - Complex/nested conditionals
            - Missing or inadequate error messages
            - Unclear naming conventions

            ### 5. Testing & Documentation (LOW Priority)
            - Missing unit tests for new code
            - Inadequate test coverage for edge cases
            - Missing/outdated documentation
            - Missing JSDoc/docstrings

            ## Review Process

            ### Step 1: Analyze Changes
            ```bash
            gh pr diff ${{ github.event.pull_request.number || github.event.issue.number }}
            ```

            ### Step 2: Create Inline Comments
            For each issue found, use `mcp__github_inline_comment__create_inline_comment` to add a comment directly on the problematic line with:
            - Severity indicator: 🔴 CRITICAL | 🟠 HIGH | 🟡 MEDIUM | 🔵 LOW
            - Clear description of the issue
            - Suggested fix or code example

            ### Step 3: Create Individual Linear Tickets
            **IMPORTANT**: Create a SEPARATE Linear ticket for EACH distinct issue found (not one combined ticket).

            First, get available teams:
            ```
            Use mcp__linear__get_teams to find available teams
            ```

            Then for EACH issue, create a ticket using `mcp__linear__create_issue` with these parameters:

            **Required:**
            - `title`: `[<SEVERITY>] <Brief issue description> - PR #${{ github.event.pull_request.number || github.event.issue.number }}`
            - `team_id`: Team ID (use from get_teams or the default LINEAR_TEAM_ID)

            **Recommended:**
            - `description`: Markdown formatted description:
              ```markdown
              ## Issue Description
              <Detailed explanation>

              ## Location
              - **File**: `path/to/file.ts`
              - **Line(s)**: 42-45

              ## Code Snippet
              ```typescript
              // Problematic code here
              ```

              ## Suggested Fix
              <How to resolve>

              ## References
              - PR: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number || github.event.issue.number }}
              - Author: @${{ github.event.pull_request.user.login || github.event.issue.user.login }}
              ```
            - `priority`: 1=Urgent (CRITICAL), 2=High, 3=Normal (MEDIUM), 4=Low
            - `label_ids`: Label IDs matching severity and category (get from `mcp__linear__get_labels`)

            **Priority Mapping:**
            | Severity | Priority | Linear Priority |
            |----------|----------|-----------------|
            | CRITICAL | 1        | Urgent          |
            | HIGH     | 2        | High            |
            | MEDIUM   | 3        | Normal          |
            | LOW      | 4        | Low             |

            ### Step 4: Post Summary Comment
            Post a summary comment on the PR with:

            ```markdown
            ## 🔍 Code Review Summary

            ### Overview
            <Brief assessment of the PR quality>

            ### Issues Found

            | Severity | Issue | File | Linear Ticket |
            |----------|-------|------|---------------|
            | 🔴 CRITICAL | <description> | `file.ts:42` | [ABC-123](url) |
            | 🟠 HIGH | <description> | `file.ts:100` | [ABC-124](url) |
            | 🟡 MEDIUM | <description> | `file.ts:200` | [ABC-125](url) |

            ### Statistics
            - 🔴 Critical: X issues
            - 🟠 High: X issues
            - 🟡 Medium: X issues
            - 🔵 Low: X issues
            - **Total**: X issues

            ### Recommendations
            <Prioritized list of what to fix first>

            ---
            *Review performed by Claude Code Action with Linear integration*
            ```

            ## Important Guidelines
            - Create tickets ONLY for issues in the changed files (not pre-existing code)
            - Each ticket should be atomic and independently actionable
            - Group related sub-issues only if they're in the same function/context
            - Always link tickets back to the PR
            - If no issues found, post a positive summary (no tickets needed)
            - Collect all Linear ticket identifiers to include in the summary table

          # Tools configuration (Linear tools auto-enabled when linear_api_key is provided)
          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,mcp__linear__get_teams,mcp__linear__get_workflow_states,mcp__linear__get_labels,mcp__linear__create_issue,mcp__linear__update_issue,mcp__linear__search_issues,mcp__linear__get_issue,mcp__linear__add_comment,mcp__linear__get_viewer,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr checks:*)"
            --max-turns 50

          # Additional CI access for context
          additional_permissions: |
            actions: read

# =============================================================================
# Setup Instructions
# =============================================================================
#
# 1. Required GitHub Secrets:
#    - CLAUDE_CODE_OAUTH_TOKEN: Run `claude setup-token` to generate
#    - LINEAR_API_KEY: Create at https://linear.app/settings/api
#
# 2. Optional GitHub Secrets:
#    - LINEAR_TEAM_ID: Default team for ticket creation (auto-detected if not set)
#
# 3. Linear MCP Server:
#    The action automatically configures the built-in Linear MCP server when
#    linear_api_key is provided. No additional MCP configuration needed.
#
# 4. Available Linear MCP Tools:
#    - mcp__linear__get_teams: List available teams
#    - mcp__linear__get_workflow_states: Get team workflow states
#    - mcp__linear__get_labels: Get team labels
#    - mcp__linear__create_issue: Create a new issue
#    - mcp__linear__update_issue: Update an existing issue
#    - mcp__linear__search_issues: Search issues
#    - mcp__linear__get_issue: Get issue details
#    - mcp__linear__add_comment: Add comment to issue
#    - mcp__linear__get_viewer: Get authenticated user info
#
# 5. Recommended Linear Labels (create in Linear if not exists):
#    - Severity: critical, high-priority, medium-priority, low-priority
#    - Category: security, bug, performance, code-quality, testing, documentation
#
# 6. Alternative Authentication:
#    - Anthropic API: Replace oauth token with anthropic_api_key
#    - AWS Bedrock: Add use_bedrock: "true"
#    - Google Vertex: Add use_vertex: "true"
#
# =============================================================================
# How It Works
# =============================================================================
#
# When track_progress is enabled:
# - Creates a tracking comment with progress checkboxes
# - Includes all PR context (comments, attachments, images)
# - Updates progress as the review proceeds
# - Marks as completed when done
#
# Linear Integration:
# - Creates INDIVIDUAL tickets for each issue (not consolidated)
# - Each ticket includes severity, description, code location
# - Links back to the PR for full context
# - Priority set based on severity level
#
# Example Output:
# For a PR with 3 issues, Claude will create:
# - ABC-101: [CRITICAL] SQL injection in user query - PR #42
# - ABC-102: [HIGH] Missing null check in handler - PR #42
# - ABC-103: [MEDIUM] Duplicate code in validation - PR #42
#
# =============================================================================
