# PR Review with Linear Integration
#
# This workflow automatically reviews PRs and creates Linear tickets for issues found.
# Uses Claude Code OAuth token for authentication.
#
# Setup required:
# 1. Add CLAUDE_CODE_OAUTH_TOKEN to repository secrets (run `claude setup-token` locally)
# 2. Add LINEAR_API_KEY to repository secrets
# 3. Optionally add LINEAR_TEAM_ID if you want to target a specific team

name: Claude PR Review with Linear

on:
  # Auto-review on PR open/update
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

  # Manual re-review via @claude comment
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  claude-review:
    # Run on PR events OR when @claude is mentioned
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude') && github.event.issue.pull_request) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Run Claude PR Review with Linear
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          # Use OAuth token (Pro/Max users - run `claude setup-token` to generate)
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Enable progress tracking comments
          track_progress: true

          # Linear Integration
          linear_api_key: ${{ secrets.LINEAR_API_KEY }}
          # Optional: Specify default team (Claude will auto-detect if not provided)
          # linear_team_id: ${{ secrets.LINEAR_TEAM_ID }}

          # Review instructions
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}

            ## Task
            Perform a comprehensive code review of this pull request.

            ## Review Focus Areas
            1. **Code Quality**
               - Clean code principles
               - SOLID principles adherence
               - Code duplication
               - Naming conventions

            2. **Security**
               - OWASP Top 10 vulnerabilities
               - Hardcoded secrets/credentials
               - Input validation
               - Authentication/authorization issues

            3. **Performance**
               - Potential bottlenecks
               - Memory leaks
               - Inefficient algorithms
               - Database query optimization

            4. **Testing**
               - Test coverage
               - Edge cases
               - Integration tests

            ## Actions
            1. Use `gh pr diff` to review all changes
            2. Use `mcp__github_inline_comment__create_inline_comment` for specific code issues
            3. Post a summary comment with overall assessment

            ## Linear Ticket Creation
            If you find CRITICAL or HIGH severity issues:
            1. First, use `mcp__linear__get_teams` to find available teams
            2. Create a Linear ticket using `mcp__linear__create_issue` with:
               - Title: "[PR Review] Critical issues in PR #${{ github.event.pull_request.number || github.event.issue.number }}"
               - Description: Summary of issues with severity levels
               - Priority: 1 (Urgent) for critical, 2 (High) for high severity
               - Include PR link: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number || github.event.issue.number }}

            ## Severity Definitions
            - CRITICAL: Security vulnerabilities, data loss potential
            - HIGH: Significant bugs, performance issues
            - MEDIUM: Code quality issues, minor bugs
            - LOW: Style issues, suggestions

          # Tools for PR review and Linear integration
          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,mcp__linear__*,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*)"
            --max-turns 30

# When track_progress is enabled:
# - Creates a tracking comment with progress checkboxes
# - Includes all PR context (comments, attachments, images)
# - Updates progress as the review proceeds
# - Marks as completed when done
#
# Linear Integration:
# - Claude can create tickets for issues found
# - Tickets include PR link and severity
# - Auto-assigns to appropriate team
