name: Revo PR Review

on:
  # Auto-review on PR open/update (skip draft PRs via job condition)
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

  # Manual re-review via @claude comment
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

# Prevent concurrent reviews on same PR
concurrency:
  group: claude-review-${{ github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: true

jobs:
  claude-review:
    # Run on non-draft PR events OR when @claude is mentioned in comments
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.draft == false) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude') && github.event.issue.pull_request) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude PR Review with Linear
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          # Authentication (choose one)
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          # anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # Enable progress tracking
          track_progress: true

          # Linear Integration (built-in MCP server)
          linear_api_key: ${{ secrets.LINEAR_API_KEY }}
          # Optional: Specify default team (Claude will auto-detect if not provided)
          linear_team_id: ${{ secrets.LINEAR_TEAM_ID }}

          # Review instructions with Linear integration
          prompt: |
            You are a senior staff engineer performing a precise, high-signal code review.
            Your goal is to find real, impactful issues — not to generate noise. Every comment
            you make should be something a senior engineer would genuinely flag in a real review.

            ## Context
            - **Repository**: ${{ github.repository }}
            - **PR**: #${{ github.event.pull_request.number || github.event.issue.number }}
            - **Title**: ${{ github.event.pull_request.title || github.event.issue.title }}
            - **Author**: @${{ github.event.pull_request.user.login || github.event.issue.user.login }}
            - **Base branch**: ${{ github.event.pull_request.base.ref || 'main' }}
            - **URL**: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number || github.event.issue.number }}

            ## Phase 1: Understand the Codebase Context

            Before reviewing any code, build understanding of the project conventions:

            1. **Read project documentation** (if they exist — skip any that don't):
               - `CLAUDE.md` — project-specific AI instructions and conventions
               - `CONTRIBUTING.md` — contribution guidelines
               - `docs/` or `documentation/` folder — architecture docs, ADRs, style guides
               - `.github/PULL_REQUEST_TEMPLATE.md` — expected PR structure
               - `README.md` — project overview, tech stack, patterns

            2. **Read configuration files** to understand the tech stack:
               - `package.json`, `tsconfig.json`, `pyproject.toml`, `Cargo.toml`, etc.
               - Linter configs (`.eslintrc`, `.prettierrc`, `ruff.toml`, `.rubocop.yml`)
               - Test configs (`jest.config`, `vitest.config`, `pytest.ini`)

            3. **Examine existing patterns** — look at 2-3 files similar to those changed
               to understand the established conventions (naming, error handling, patterns).

            This context is critical. Review violations of PROJECT conventions, not generic
            best practices the project intentionally doesn't follow.

            ## Phase 2: Analyze the Diff

            Retrieve the full diff:
            ```bash
            gh pr diff ${{ github.event.pull_request.number || github.event.issue.number }}
            ```

            Also retrieve the PR description and any linked issues for intent:
            ```bash
            gh pr view ${{ github.event.pull_request.number || github.event.issue.number }}
            ```

            Read each changed file IN FULL (not just the diff hunks) to understand the
            complete context around changes. A line that looks wrong in isolation may be
            correct in context.

            ## Phase 3: Deep Analysis with Sequential Thinking

            Before posting any comments, use `mcp__sequential_thinking__sequentialthinking`
            to reason through the changes systematically. This structured thinking prevents
            false positives and ensures you only flag real issues.

            Use sequential thinking for:
            - **Security analysis**: Trace data flow from user input through the changed code
              to identify real injection/auth vulnerabilities (not theoretical ones).
            - **Bug analysis**: Walk through execution paths step by step to confirm a bug
              actually triggers in practice, not just in theory.
            - **Architecture evaluation**: Think through how the changes interact with the
              rest of the system before flagging design issues.
            - **Confidence calibration**: For each potential issue, use a thought to ask
              "Am I confident this is a real problem, or am I guessing?" Only flag if confident.

            Example usage — start with thought 1, estimate total thoughts, and continue:
            ```
            Thought 1/4: "Looking at the diff, there are 3 changed files. The auth handler
            change modifies token validation. Let me trace the token flow..."
            Thought 2/4: "The token is received from req.headers, passed to validateToken()
            which... [traces the full path]. This IS vulnerable because..."
            Thought 3/4: "The second file changes a database query. The input comes from...
            and IS properly parameterized, so this is NOT an injection risk."
            Thought 4/4: "Summary: 1 confirmed security issue, 1 false positive avoided."
            ```

            Use branching when you need to explore alternative interpretations:
            - Branch to evaluate "is this a bug or intentional behavior?"
            - Branch to compare "fix option A vs fix option B" for suggestions

            ## Phase 4: Review with Precision

            Apply the following review criteria. **Only flag issues you are confident about.**
            If you are unsure whether something is a real issue, do NOT flag it.

            ### CRITICAL — Must fix before merge (blocks shipment)
            - **Security vulnerabilities**: injection (SQL, XSS, command), auth bypass,
              secrets in code, path traversal, SSRF, insecure deserialization
            - **Data loss or corruption**: writes without transactions where needed,
              race conditions on shared state, missing cascading deletes
            - **Breaking changes**: API contract violations, removed public interfaces
              without deprecation

            ### HIGH — Should fix before merge (significant risk)
            - **Bugs**: logic errors, incorrect boundary conditions, null/undefined in
              paths that will be hit, unhandled error cases that cause crashes
            - **Resource leaks**: unclosed connections, missing cleanup in error paths,
              event listener accumulation
            - **Concurrency issues**: race conditions, deadlock potential, unsafe shared
              mutation

            ### MEDIUM — Should fix soon (tech debt with real cost)
            - **Performance**: N+1 queries, O(n^2) where O(n) is straightforward,
              unbounded collection growth, missing pagination on user-facing queries
            - **Error handling**: swallowed exceptions hiding failures, missing error
              context making debugging hard, catch blocks that silently continue
            - **Convention violations**: patterns that contradict the project's established
              conventions (found in Phase 1)

            ### LOW — Consider improving (nice to have)
            - **Readability**: confusing variable names in complex logic, deeply nested
              conditionals that could be flattened, large functions doing multiple things
            - **Test gaps**: new non-trivial logic without test coverage, missing edge case
              tests for complex branching

            ### DO NOT flag (these create noise)
            - Style issues already handled by linters/formatters
            - Missing docs on self-explanatory code
            - "Could be slightly more efficient" without measurable impact
            - Personal preferences that don't match project conventions
            - Pre-existing issues in unchanged code
            - Generic best-practice suggestions the codebase doesn't follow
            - Trivial naming suggestions unless genuinely confusing

            ## Phase 5: Post Inline Comments

            For each real issue found, use `mcp__github_inline_comment__create_inline_comment`
            to comment directly on the problematic line(s).

            Format each comment as:

            **[SEVERITY]** Brief one-line description

            <explanation — 2-3 sentences max, explain WHY this is a problem and what
            the concrete risk is>

            ```suggestion
            // concrete fix if applicable — use GitHub suggestion blocks so the
            // author can apply with one click
            ```

            Rules for inline comments:
            - **One issue per comment.** Don't bundle unrelated issues.
            - **Be specific.** Say "this query runs per item in the loop (N+1)" not
              "consider performance."
            - **Always explain the risk.** Not just "this is wrong" but "this will throw
              at runtime when X is null because Y."
            - **Provide a fix when possible.** Use ```suggestion blocks for single-line
              or multi-line replacements.
            - **Comment on the RIGHT side** of the diff (new code), not the left.

            ## Phase 6: Create Linear Tickets

            Create a SEPARATE Linear ticket for EACH issue rated CRITICAL or HIGH.
            MEDIUM issues should be grouped into a single ticket if there are 3+,
            otherwise create individual tickets. Do NOT create tickets for LOW issues.

            ### Setup
            1. Get available teams: use `mcp__linear__get_teams`
            2. Get available labels: use `mcp__linear__get_labels` (with team_id if available)

            ### For each ticket, use `mcp__linear__create_issue` with:

            - **title**: `[SEVERITY] Brief description — PR #${{ github.event.pull_request.number || github.event.issue.number }}`
            - **team_id**: From get_teams or LINEAR_TEAM_ID
            - **priority**: 1 (CRITICAL=Urgent), 2 (HIGH=High), 3 (MEDIUM=Normal)
            - **description** (markdown):

              ```
              ## What
              <One paragraph: what the issue is and why it matters>

              ## Where
              **File:** `path/to/file.ts`
              **Lines:** 42-45
              **Function/Method:** `handleUserInput()`

              ## Evidence
              ```<lang>
              // the problematic code
              ```

              ## Suggested Fix
              ```<lang>
              // the corrected code
              ```

              ## Impact
              <What happens if this is not fixed — be concrete>

              ## References
              - PR: ${{ github.repository }}#${{ github.event.pull_request.number || github.event.issue.number }}
              ```

            - **label_ids**: Match severity + category labels from `get_labels`

            ### Deduplication
            Before creating a ticket, use `mcp__linear__search_issues` to check if a
            similar issue already exists for this PR. Search for the PR number in existing
            issues. Skip creation if a matching ticket already exists.

            ## Phase 7: Post Summary Comment

            After all inline comments and tickets are created, post a single summary
            comment on the PR using `gh pr comment`:

            ```markdown
            ## Code Review Summary

            **Verdict**: <APPROVE / REQUEST_CHANGES / NEEDS_DISCUSSION>

            ### What This PR Does
            <2-3 sentence summary of the changes and their purpose>

            ### Issues Found

            | # | Severity | Issue | Location | Linear |
            |---|----------|-------|----------|--------|
            | 1 | CRITICAL | <description> | `file.ts:42` | [TEAM-123](url) |
            | 2 | HIGH | <description> | `file.ts:100` | [TEAM-124](url) |

            <If no issues: "No issues found. This PR looks good to merge.">

            ### What Went Well
            <1-3 things done well in this PR — be genuine, not generic>

            ### Recommendation
            <Clear next step: "Fix the 1 critical issue and this is good to merge"
            or "Looks great, ship it">
            ```

            ## Critical Rules
            - **Only review changed code.** Never flag pre-existing issues.
            - **Precision over recall.** 3 real issues > 10 issues where 7 are noise.
            - **Respect project conventions.** If the codebase uses a pattern, don't flag it.
            - **Read before judging.** Always read the full file, not just diff hunks.
            - **Be actionable.** Every comment must have a clear "what to do next."
            - **Skip if clean.** If the PR is well-written, say so and approve. Don't
              manufacture issues to justify the review.
            - **No duplicate tickets.** Always search Linear before creating.

          # Tools configuration
          claude_args: |
            --allowedTools "Read,Glob,Grep,LS,mcp__sequential_thinking__sequentialthinking,mcp__github_inline_comment__create_inline_comment,mcp__linear__get_teams,mcp__linear__get_workflow_states,mcp__linear__get_labels,mcp__linear__create_issue,mcp__linear__update_issue,mcp__linear__search_issues,mcp__linear__get_issue,mcp__linear__add_comment,mcp__linear__get_viewer,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr checks:*),Bash(cat:*),Bash(ls:*)"
            --max-turns 50

          # Additional CI access for context
          additional_permissions: |
            actions: read

# =============================================================================
# Setup Instructions
# =============================================================================
#
# 1. Required GitHub Secrets:
#    - CLAUDE_CODE_OAUTH_TOKEN: Run `claude setup-token` to generate
#      OR ANTHROPIC_API_KEY: Your Anthropic API key
#    - LINEAR_API_KEY: Create at https://linear.app/settings/api
#
# 2. Optional GitHub Secrets:
#    - LINEAR_TEAM_ID: Default team for ticket creation (auto-detected if not set)
#
# 3. Linear MCP Server:
#    The action automatically configures the built-in Linear MCP server when
#    linear_api_key is provided. No additional MCP configuration needed.
#
# 4. Available Linear MCP Tools:
#    - mcp__linear__get_teams: List available teams
#    - mcp__linear__get_workflow_states: Get team workflow states
#    - mcp__linear__get_labels: Get team labels
#    - mcp__linear__create_issue: Create a new issue
#    - mcp__linear__update_issue: Update an existing issue
#    - mcp__linear__search_issues: Search issues
#    - mcp__linear__get_issue: Get issue details
#    - mcp__linear__add_comment: Add comment to issue
#    - mcp__linear__get_viewer: Get authenticated user info
#
# 5. Sequential Thinking MCP Tool:
#    - mcp__sequential_thinking__sequentialthinking: Structured reasoning
#    Automatically enabled when included in allowedTools. No config needed.
#    Helps Claude think through complex code paths before commenting.
#
# 6. Recommended Linear Labels (create in Linear if not exists):
#    Severity: critical, high, medium, low
#    Category: security, bug, performance, code-quality
#
# 7. Alternative Authentication:
#    - Anthropic API: Replace oauth token with anthropic_api_key
#    - AWS Bedrock: Add use_bedrock: "true"
#    - Google Vertex: Add use_vertex: "true"
#
# =============================================================================
# How It Works
# =============================================================================
#
# The review follows a 7-phase process:
#
# Phase 1 — Context: Reads CLAUDE.md, CONTRIBUTING.md, docs/, configs
#   to understand the project's conventions before reviewing.
#
# Phase 2 — Diff Analysis: Retrieves the full diff and reads changed
#   files completely (not just hunks) for full context.
#
# Phase 3 — Sequential Thinking: Uses the sequential thinking MCP tool
#   to reason through changes step-by-step. Traces data flows, confirms
#   bugs actually trigger, and calibrates confidence before flagging.
#   This phase eliminates false positives.
#
# Phase 4 — Precision Review: Applies a strict severity framework
#   focused on real issues. Explicitly avoids noise (style nits,
#   pre-existing issues, personal preferences).
#
# Phase 5 — Inline Comments: Posts actionable comments with severity
#   tags and GitHub suggestion blocks for one-click fixes.
#
# Phase 6 — Linear Tickets: Creates individual tickets for CRITICAL
#   and HIGH issues, with deduplication checks. MEDIUM issues are
#   grouped. LOW issues get inline comments only.
#
# Phase 7 — Summary: Posts a verdict (APPROVE/REQUEST_CHANGES) with
#   an issues table, what went well, and clear next steps.
#
# Example Output:
# For a PR with 3 issues, Claude will create:
# - ABC-101: [CRITICAL] SQL injection in user query — PR #42
# - ABC-102: [HIGH] Missing null check in handler — PR #42
# - ABC-103: [MEDIUM] Grouped: 3 code quality improvements — PR #42
#
# =============================================================================
